# Generated by Django 5.0.14 on 2025-12-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='author_avatar',
            field=models.URLField(blank=True, help_text='URL de la imagen de perfil del autor', null=True),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='author_avatar',
            field=models.URLField(blank=True, help_text='URL de la imagen de perfil del autor', null=True),
        ),
    ]
