# Generated by Django 5.0.14 on 2025-12-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forumcomment_author_avatar_forumpost_author_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='author_avatar',
            field=models.TextField(blank=True, help_text='URL o data URI de la imagen de perfil del autor', null=True),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='author_avatar',
            field=models.TextField(blank=True, help_text='URL o data URI de la imagen de perfil del autor', null=True),
        ),
    ]
