# Generated by Django 5.0.14 on 2025-12-09 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_forumcomment_author_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ForumLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(help_text='Identificador único del usuario (email o username)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='forum.forumcomment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='forum.forumpost')),
            ],
            options={
                'verbose_name': 'Like del Foro',
                'verbose_name_plural': 'Likes del Foro',
                'unique_together': {('user_identifier', 'comment'), ('user_identifier', 'post')},
            },
        ),
    ]
